# Generated by Django 6.0.8 on 2026-09-06 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdvisoryDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "source",
                    models.CharField(
                        help_text="e.g., ICAR-DOGR, KAU, Ministry of Agriculture",
                        max_length=150,
                    ),
                ),
                (
                    "crop",
                    models.CharField(
                        db_index=True,
                        help_text="Target Crop (e.g. Onion, Wheat, Tomato, General)",
                        max_length=100,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("storage", "Post-Harvest & Storage Management"),
                            ("harvesting", "Harvesting & Best Time to Sell"),
                            ("price_cycle", "Price Trends & Seasonal Cycles"),
                            ("disease_pest", "Quality, Spoilage & Disease Management"),
                            ("export_msp", "Govt Policy, MSP & Export Dynamics"),
                            ("general", "General Agronomic Advisory"),
                        ],
                        db_index=True,
                        default="general",
                        max_length=50,
                    ),
                ),
                ("publication_date", models.DateField(blank=True, null=True)),
                ("document_text", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "advisory_documents",
            },
        ),
        migrations.CreateModel(
            name="QueryAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query_text", models.TextField()),
                ("detected_language", models.CharField(default="en", max_length=20)),
                (
                    "routed_category",
                    models.CharField(
                        choices=[
                            ("STRUCTURED", "Purely Structured (SQL)"),
                            ("UNSTRUCTURED", "Purely Unstructured (RAG)"),
                            ("HYBRID", "Hybrid (SQL + RAG)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("extracted_entities", models.JSONField(blank=True, default=dict)),
                ("sql_query", models.TextField(blank=True, null=True)),
                ("sql_results_count", models.IntegerField(default=0)),
                ("chunks_retrieved_count", models.IntegerField(default=0)),
                ("response_text", models.TextField()),
                ("decision_action", models.CharField(blank=True, max_length=50)),
                (
                    "confidence_score",
                    models.CharField(
                        choices=[
                            ("HIGH", "High Confidence"),
                            ("MEDIUM", "Medium Confidence"),
                            ("LOW", "Low / Uncertain"),
                        ],
                        default="HIGH",
                        max_length=20,
                    ),
                ),
                ("uncertainty_reason", models.TextField(blank=True)),
                ("sources_cited", models.JSONField(blank=True, default=list)),
                ("execution_time_ms", models.FloatField(default=0.0)),
                ("tokens_used", models.IntegerField(default=0)),
                ("is_cached", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "query_audit_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MandiPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(db_index=True, max_length=100)),
                ("district", models.CharField(db_index=True, max_length=100)),
                ("market", models.CharField(db_index=True, max_length=150)),
                ("commodity", models.CharField(db_index=True, max_length=100)),
                ("variety", models.CharField(default="Other", max_length=100)),
                ("grade", models.CharField(default="FAQ", max_length=50)),
                ("arrival_date", models.DateField(db_index=True)),
                (
                    "min_price",
                    models.DecimalField(
                        decimal_places=2, help_text="Price in Rs/Quintal", max_digits=10
                    ),
                ),
                (
                    "max_price",
                    models.DecimalField(
                        decimal_places=2, help_text="Price in Rs/Quintal", max_digits=10
                    ),
                ),
                (
                    "modal_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Modal/Average Price in Rs/Quintal",
                        max_digits=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "mandi_prices",
                "indexes": [
                    models.Index(
                        fields=["commodity", "state", "arrival_date"],
                        name="mandi_price_commodi_b961ea_idx",
                    ),
                    models.Index(
                        fields=["commodity", "market", "arrival_date"],
                        name="mandi_price_commodi_0b366d_idx",
                    ),
                    models.Index(
                        fields=["arrival_date"], name="mandi_price_arrival_651466_idx"
                    ),
                ],
                "unique_together": {
                    ("commodity", "state", "market", "variety", "arrival_date")
                },
            },
        ),
        migrations.CreateModel(
            name="AdvisoryChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crop", models.CharField(db_index=True, max_length=100)),
                ("topic", models.CharField(blank=True, max_length=150)),
                ("chunk_index", models.IntegerField(default=0)),
                ("content", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "embedding_json",
                    models.TextField(
                        blank=True,
                        help_text="JSON string array for sqlite/mock fallback",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="advisor.advisorydocument",
                    ),
                ),
            ],
            options={
                "db_table": "advisory_chunks",
                "indexes": [
                    models.Index(
                        fields=["crop", "topic"], name="advisory_ch_crop_1c2fd5_idx"
                    )
                ],
            },
        ),
    ]
